# config/sources/customers_csv.yaml
name: customers_csv
connector: filesystem
path: file:///workspace/data/customers.csv
format: csv
format_options:
  csv.field-delimiter: ","
  csv.ignore-parse-errors: "true"

schema:
  - name: legal_entity
    type: string
  - name: local_cif
    type: string
  - name: id
    type: string
  - name: id_type
    type: string
  - name: id_issuing_country
    type: string
  - name: name
    type: string
  - name: email
    type: string
  - name: phone
    type: string
  - name: address
    type: string

